Repository prgrms-web-devcourse-final-project/WEB5_6_GitSunJaeAb_BE, pull requests merged in 2025-07, with the labels that each got.

#42 (0724) refactor: 알림 - 알림 조회 시 권한 체크 추가 (본인 알림만 조회) (03:55)
  MAPICK/src/main/java/com/gitsunjaeab/mapick/api/notification/NotificationController.java
  MAPICK/src/main/java/com/gitsunjaeab/mapick/application/notification/NotificationService.java
  MAPICK/src/main/java/com/gitsunjaeab/mapick/domain/notification/Notification.java
  MAPICK/src/main/java/com/gitsunjaeab/mapick/domain/notification/NotificationRepository.java
Labels: 알림

#44 (0724) refactor: 공지 - 공지 응답바디에 announcementType 추가 (15:02)
  MAPICK/src/main/java/com/gitsunjaeab/mapick/api/notification/dto/AnnouncementSimpleDTO.java
Labels: 공지

#100 (0731) refactor : 디렉토리 정리
  MAPICK/src/main/java/com/gitsunjaeab/mapick/application/domain/quest/MemberQuestService.java
Labels: 퀘스트
